services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:14250
    depends_on:
      - jaeger

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
